UPLOAD_SERVICE_INSTALL_PATH=~/Library/Services/
SCREENSHOT_SERVICE_INSTALL_PATH=~/Library/Workflows/Applications/Folder\ Actions/
IMGURU_INSTALL_PATH=/usr/local/bin

IMGUR_SCREENSHOT_WORKFLOW=imgur-screenshot-upload.workflow
IMGUR_UPLOAD_WORKFLOW=imgur-upload.workflow

AUTOMATOR_IMGUR_SCREENSHOT_UPLOAD_DIR=./automator/$IMGUR_SCREENSHOT_WORKFLOW
AUTOMATOR_IMGUR_UPLOAD_DIR=./automator/$IMGUR_UPLOAD_WORKFLOW

